accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.user_list, name='user_list'),
    path('<int:id>/', views.user_page, name='user_page'),
    
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    
    path('follow/<int:id>', views.follow, name='follow'),
    path('<int:id>/followers/', views.followers, name='followers'),
    path('<int:id>/followings/', views.followings, name='followings'),
]

movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/', views.detail, name='detail'),
    
    path('<int:id>/scores/new/', views.scores_new, name='scores_new'),
    path('<int:id>/scores/<int:score_id>/delete', views.score_delete, name='score_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings

# Create your models here.
class User(AbstractUser):
    from_user = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="to_user", blank=True)

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

class Score(models.Model):
    content = models.CharField(max_length=100)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    class Meta:
        ordering=['-value',]
    

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

movies/forms.py
from django import forms
from .models import Genre, Movie, Score

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields = '__all__'
        
class ScoreForm(forms.ModelForm):
    class Meta:
        model=Score
        fields=['content','value',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import get_user_model

from .forms import UserCustomCreationForm
# Create your views here.

def user_list(request):
    User = get_user_model()
    users = User.objects.all()
    return render(request, 'accounts/user_list.html', {'users':users})
    
def user_page(request, id):
    User = get_user_model()
    user_info = User.objects.get(id=id)
    return render(request, 'accounts/user_page.html', {'user_info':user_info})
    
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')
    
@login_required
def follow(request, id):
    User = get_user_model()
    me = request.user
    you = User.objects.get(id=id)
    
    if me != you:
        if you in me.from_user.all():
            me.from_user.remove(you)
        else:
            me.from_user.add(you)
    return redirect('accounts:user_page', id)

def followers(request, id):
    User = get_user_model()
    user = User.objects.get(id=id)
    follows = user.to_user.all()
    return render(request, 'accounts/follow.html',{'follows':follows,'user':user})
    
def followings(request, id):
    User = get_user_model()
    user = User.objects.get(id=id)
    follows = user.from_user.all()
    return render(request, 'accounts/follow.html',{'follows':follows,'user':user})

movies/views.py
from django.shortcuts import render,redirect
from .models import Movie,Score
from .forms import ScoreForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST


# Create your views here.
def list(request):
    movie = Movie.objects.all()
    return render(request, 'movies/list.html', {'movies':movie})
    
def detail(request, id):
    movie = Movie.objects.get(id=id)
    form = ScoreForm()
    return render(request, 'movies/detail.html', {'movie':movie, 'form':form})
    
@login_required
def scores_new(request,id):
    movie=Movie.objects.get(id=id)
    if request.method=="POST":
        form=ScoreForm(request.POST)
        if form.is_valid():
            score = form.save(commit=False)
            score.movie=movie
            score.user=request.user
            score.save()
            return redirect('movies:detail', id)
            
@login_required
@require_POST
def score_delete(request, id, score_id):
    score=Score.objects.get(id=score_id)
    if request.user==score.user:
        score.delete()
    return redirect('movies:detail', id)

accounts/templates/accounts/follow.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{user.username}}</h1>
    {% if request.resolver_match.url_name == 'followers' %}
        <h5>팔로워 {{user.to_user.count}} 명</h5>
    {% elif request.resolver_match.url_name == 'followings' %}
        <h5>팔로잉 {{user.from_user.count}} 명</h5>
    {% endif %}
    
    {% for follow in follows %}
        <p>{{follow.username}}</p>
    {% endfor %}
    
{% endblock %}

accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="!">
</form>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends 'base.html' %}

{% block body %}
    {{user_info.username}}
    {% if user != user_info %}
        {% if user_info in user.from_user.all %}
            <a href="{% url 'accounts:follow' user_info.id %}">팔로잉</a>
        {% else %}
            <a href="{% url 'accounts:follow' user_info.id %}">팔로우</a>
        {% endif %}
    {% endif %}
{% endblock %}

accounts/templates/accounts/user_list.html
{% extends 'base.html' %}

{% block body %}
    <h1>유저 목록</h1>
    {% for user in users %}
        <a href="{% url 'accounts:user_page' user.id %}">{{user}}</a>
    {% endfor %}
{% endblock %}

accounts/templates/accounts/user_page.html
{% extends 'base.html' %}

{% block body %}
    <h1>{{user_info.username}}</h1>
    
    {% if user != user_info %}
        {% if user_info in user.from_user.all %}
            <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-light">팔로잉</a>
        {% else %}
            <a href="{% url 'accounts:follow' user_info.id %}" class="btn btn-primary">팔로우</a>
        {% endif %}
    {% else %}
        {% for follow in user.from_user.all %}
            <h4>{{follow.username}} 님의 추천 영화</h4>
            <p>{{follow.score_set.first.movie.title}} {{follow.score_set.first.value}}</p>
        {% endfor %}
    {% endif %}
    
    <h4>팔로잉 <a href="{% url 'accounts:followings' user_info.id %}">{{user_info.from_user.count}}</a></h4>
    <h4>팔로워 <a href="{% url 'accounts:followers' user_info.id %}">{{user_info.to_user.count}}</a></h4>
    <br>
    
    <h4>평점정보</h4>
    {% for score in user_info.score_set.all %}
        <p>{{score.movie.title}} : {{score.value}} 점</p>
    {% endfor %}
    
    
{% endblock %}

movie_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% if user.is_authenticated %}
        <p>{{ user.username }}</p>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        <a href="{% url 'accounts:login' %}">로그인</a>
    {% endif %}
    
    <a href="{% url 'movies:list' %}">영화목록</a>
    <a href="{% url 'accounts:user_list' %}">유저목록</a>
    <hr> 
    <div class="container my-5">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block body %}
<h1>{{movie.title}}</h1>
<h5>누적관객수 : {{movie.audience}}</h5>
<h5>포스터 : <img src="{{movie.poster_url}}"></img></h5>
<h5>영화소개 : {{movie.description}}</h5>

{% for score in movie.score_set.all %}
    <p>{{score.user.username}}</p>
    <p>한줄평 : {{score.content}}</p>
    <p>평점 : {{score.value}}</p>
    {% if score.user == user %}
        <form action="{% url 'movies:score_delete' movie.id score.id %}" method='post'>
            {% csrf_token %}
            <input type="submit" value="삭제">
        </form>
    {% endif %}
    <hr>
{% endfor %}

<form action="{% url 'movies:scores_new' movie.id %}" method="post">
    {% csrf_token %}
    <div>한줄평 {{form.content}}</div>
    <div>평점 {{form.value}}</div>
    <input type="submit" value="submit">
</form>
{% endblock %}

movies/templates/movies/list.html
{% extends 'base.html' %}
{% block body %}
<h1>Movies List</h1>
    {% for movie in movies %}
        <div class="card my-3" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{movie.title}}</h5>
                <a href="{% url 'movies:detail' movie.id%}"><img src="{{movie.poster_url}}"></img></a>
            </div>
        </div>
    {% endfor %}
{% endblock %}